server.port=8082

# FHNW MySQL-Server, nur via VPN erreichbar
spring.datasource.url=jdbc:mysql://192.168.111.13/vl_custmgmt?allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=vl_custmgmt
spring.datasource.password=d854hg23t48+f2z-fvtz8tb0b4v
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


clientdata.sql.findByCustomerReference=SELECT c.custId AS customerReference, CONCAT(a.street, ', ', a.zip, ' ', a.town) AS destination, c.phone AS recepientPhone, c.email AS email FROM customer c JOIN customerAddress a ON c.custId = a.custId WHERE c.custId = ? AND a.type = 'shipping' LIMIT 1